version: '3.4'
services:

  front-react:
    container_name: front-react
    build:
        context: .
        dockerfile: ./Dockerfiles/node.dockerfile
        target: dev
    volumes:
        - './front:/app'
    ports:
        - '3000:3000'
    environment:
        - CHOKIDAR_USEPOLLING=true
    depends_on: 
        - webserver

  #PHP Service
  api-lumen:
    build:
      context: .
      dockerfile: ./Dockerfiles/php.dockerfile
    container_name: api-lumen
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./api:/var/www
    depends_on: 
        - mysql-db

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./api:/var/www
      - ./resources/nginx/conf.d/:/etc/nginx/conf.d/
    depends_on: 
       - api-lumen

  #MySQL Service
  mysql-db:
    image: mysql
    container_name: mysql-db
    restart: unless-stopped
    command: mysqld --default-authentication-plugin=mysql_native_password
    environment:
        - MYSQL_ROOT_PASSWORD=mysecretpass
    volumes:
      - ./dbdata:/var/lib/mysql/
    #   - ./resources/mysql/my.cnf:/etc/mysql/my.cnf
    env_file: 
        - ./secret.env
    ports:
      - "3306:3306"